import { Link } from 'react-router-dom';
import './AboutPage.css';

export function HelpPage() {
  return (
    <article className="about-page">
      <h1 className="about-page__title">Help</h1>

      <h2 className="about-page__heading">Pinning stories</h2>
      <p>
        Pin a story to keep it in your reading list. Use it as a
        to-read list: pin the ones you want to read, then sweep the rest.
      </p>
      <ul>
        <li>
          Tap the <strong>📌 pin</strong> on the right of any row to
          pin it. Tap again to unpin.
        </li>
        <li>
          <strong>Swipe a story left</strong> for the same toggle.
        </li>
      </ul>
      <p>
        Pinned stories live in <Link to="/pinned">Pinned</Link> in the
        menu. They stay on your device until you unpin them.
      </p>

      <h2 className="about-page__heading">Favoriting stories</h2>
      <p>
        Favorites are for the ones you want to keep for good — a
        permanent keepsake shelf, separate from your pin-for-later list.
      </p>
      <ul>
        <li>
          Open a thread and tap the <strong>heart</strong> in the thread
          header to favorite. Tap again to unfavorite.
        </li>
        <li>
          Favorites never expire and are never swept.
        </li>
      </ul>
      <p>
        They live in <Link to="/favorites">Favorites</Link> in the menu.
      </p>

      <h2 className="about-page__heading">Dismissing stories</h2>
      <p>
        Dismissing hides a story you don&rsquo;t want to see in your feeds:
      </p>
      <ul>
        <li>
          <strong>Swipe a story right</strong> in any feed to dismiss it.
        </li>
        <li>
          Tap the <strong>sweep</strong> icon in the top bar to dismiss
          every unpinned story on screen at once.
        </li>
      </ul>

      <h2 className="about-page__heading">Peeking at dismissed stories</h2>
      <p>
        Tap the <strong>eye</strong> in the top bar to toggle dismissed
        stories on and off. When they&rsquo;re shown, they appear
        muted inline; tapping one opens the thread and un-dismisses it.
        Dismissed stories also live in <Link to="/ignored">Ignored</Link>,
        and dismissals expire after seven days.
      </p>

      <h2 className="about-page__heading">Undoing a dismiss</h2>
      <p>
        Tap the <strong>undo</strong> icon in the top bar to bring back
        the stories you most recently dismissed — whether you swiped
        them away one at a time or swept them all at once.
      </p>

      <h2 className="about-page__heading">The story actions menu</h2>
      <p>
        <strong>Long-press</strong> any story row to open a menu with
        quick actions: pin or unpin it, dismiss it, and{' '}
        <strong>share</strong> it. Share uses your device&rsquo;s native
        share sheet when available, and falls back to copying the link
        to the clipboard.
      </p>

      <h2 className="about-page__heading">Reading comments</h2>
      <p>
        Open a thread and every comment starts <strong>collapsed</strong>
        {' '}— you see the author, age, reply count, and the first three
        lines of the body.
      </p>
      <ul>
        <li>
          <strong>Tap a comment</strong> to expand it. The full body
          appears, and its direct replies show up below as their own
          three-line previews. Tap any of those to drill in.
        </li>
        <li>
          Tap the comment again to collapse it back.
        </li>
        <li>
          Tapping a link inside a comment opens the link — it
          doesn&rsquo;t toggle the comment.
        </li>
        <li>
          Expanded comments pick up a muted{' '}
          <strong>Reply on HN ↗</strong> link on the meta row.
          hnews.app doesn&rsquo;t submit comments itself, so that link
          hands you off to Hacker News to write the reply there.
        </li>
      </ul>

      <h2 className="about-page__heading">Article summaries</h2>
      <p>
        When a thread points to an external article, a short AI
        summary appears near the top of the thread page so you can
        size it up before tapping through. Summaries are generated by
        Gemini 2.5 Flash and may be inaccurate — treat them as a
        preview, not a substitute for the article.
      </p>

      <h2 className="about-page__heading">Recently opened</h2>
      <p>
        Stories you&rsquo;ve tapped into recently show up in{' '}
        <Link to="/opened">Opened</Link> in the menu, so you can find
        that thing you read earlier without scrolling the feed again.
        Entries here expire after seven days.
      </p>

      <h2 className="about-page__heading">Switching theme</h2>
      <p>
        Open the menu and pick <strong>Light</strong>,{' '}
        <strong>Dark</strong>, or <strong>System</strong> under Theme.
        System follows your device setting and is the default.
      </p>

      <h2 className="about-page__heading">Pinned, favorite, dismissed</h2>
      <p>
        <strong>Pin</strong> keeps a story in your short-term reading
        list. <strong>Favorite</strong> keeps it for good.{' '}
        <strong>Dismiss</strong> hides it from the feed. They&rsquo;re
        independent — you can pin and dismiss the same story (it stays
        pinned even though it&rsquo;s gone from the feed), and you can
        favorite a story whether or not it&rsquo;s pinned.
      </p>

      <p className="about-page__back">
        <Link to="/top">← Back to Top</Link>
      </p>
    </article>
  );
}
