import { useCallback, useState } from 'react';
import { Link } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import { useItemTree } from '../hooks/useItemTree';
import { useInfiniteScroll } from '../hooks/useInfiniteScroll';
import { useSavedStories } from '../hooks/useSavedStories';
import { useSummary } from '../hooks/useSummary';
import { formatTimeAgo, pluralize } from '../lib/format';
import { markArticleOpenedId } from '../lib/openedStories';
import { prefetchSavedStory } from '../lib/savedStoryPrefetch';
import { sanitizeCommentHtml } from '../lib/sanitize';
import { Comment } from './Comment';
import { ThreadSkeleton } from './Skeletons';
import { ErrorState, EmptyState } from './States';
import './Thread.css';

interface Props {
  id: number;
}

export const TOP_LEVEL_PAGE_SIZE = 20;

function SummaryCard({ url }: { url: string }) {
  const { data, isFetching, isError, error, refetch } = useSummary(url, true);
  const loading = isFetching && !data;

  return (
    <div
      className="thread__summary-card"
      data-testid="thread-summary-card"
      role="region"
      aria-label="AI summary"
      aria-live="polite"
      aria-busy={loading}
    >
      <div className="thread__summary-label">AI summary</div>
      {loading ? (
        <div
          className="thread__summary-skeleton"
          data-testid="thread-summary-skeleton"
          aria-hidden="true"
        >
          <span className="thread__summary-skeleton-line" />
          <span className="thread__summary-skeleton-line" />
          <span className="thread__summary-skeleton-line" />
          <span className="thread__summary-skeleton-line" />
          <span className="thread__summary-skeleton-line thread__summary-skeleton-line--short" />
        </div>
      ) : null}
      {loading ? (
        <span className="visually-hidden">Summarizing…</span>
      ) : null}
      {data ? <p className="thread__summary-body">{data.summary}</p> : null}
      {isError && !isFetching ? (
        <div className="thread__summary-error">
          <p>
            Could not summarize.
            {error instanceof Error && error.message
              ? ` ${error.message}.`
              : ''}
          </p>
          <button
            type="button"
            className="thread__summary-retry"
            onClick={() => refetch()}
          >
            Retry
          </button>
        </div>
      ) : null}
      <div className="thread__summary-footer">
        Generated by Gemini 2.5 Flash — may be inaccurate.
      </div>
    </div>
  );
}

export function Thread({ id }: Props) {
  const { data, isLoading, isError, refetch } = useItemTree(id);
  const queryClient = useQueryClient();
  const [visibleCount, setVisibleCount] = useState(TOP_LEVEL_PAGE_SIZE);
  const { isSaved, save, unsave } = useSavedStories();
  const saved = isSaved(id);
  const item = data?.item;
  const handleToggleSaved = useCallback(() => {
    if (saved) {
      unsave(id);
    } else {
      save(id);
      if (item) prefetchSavedStory(queryClient, item);
    }
  }, [saved, id, save, unsave, item, queryClient]);

  const kidIds = data?.kidIds ?? [];
  const shown = kidIds.slice(0, visibleCount);
  const hasMore = visibleCount < kidIds.length;

  const sentinelRef = useInfiniteScroll<HTMLDivElement>({
    enabled: hasMore,
    onLoadMore: () => setVisibleCount((n) => n + TOP_LEVEL_PAGE_SIZE),
  });

  if (isLoading) {
    return (
      <div className="thread" aria-busy="true" aria-label="Loading thread">
        <ThreadSkeleton />
      </div>
    );
  }
  if (isError) {
    return <ErrorState message="Could not load thread." onRetry={() => refetch()} />;
  }
  if (!data || !item) {
    return <EmptyState message="Item not found." />;
  }

  if (item.deleted || item.dead) {
    return (
      <div className="thread">
        <header className="thread__header">
          <h1 className="thread__title">
            {item.deleted ? '[deleted]' : '[dead]'}
          </h1>
        </header>
      </div>
    );
  }

  const age = item.time ? formatTimeAgo(item.time) : '';
  const points = item.score ?? 0;
  const commentCount = item.descendants ?? 0;

  return (
    <article className="thread">
      <header className="thread__header">
        <h1 className="thread__title">{item.title ?? '[untitled]'}</h1>
        {item.url ? <SummaryCard url={item.url} /> : null}
        {item.url ? (
          <a
            className="thread__read-article"
            href={item.url}
            target="_blank"
            rel="noopener noreferrer"
            onClick={() => markArticleOpenedId(item.id)}
          >
            Read article
          </a>
        ) : null}
        <button
          type="button"
          className={
            'thread__save' + (saved ? ' thread__save--active' : '')
          }
          data-testid="thread-save"
          aria-pressed={saved}
          onClick={handleToggleSaved}
        >
          {saved ? 'Saved' : 'Save'}
        </button>
        <div className="thread__meta">
          <span>
            {points} {pluralize(points, 'point')}
          </span>
          {item.by ? (
            <>
              <span aria-hidden="true"> · </span>
              <Link to={`/user/${item.by}`} className="thread__author">
                {item.by}
              </Link>
            </>
          ) : null}
          {age ? (
            <>
              <span aria-hidden="true"> · </span>
              <span>{age}</span>
            </>
          ) : null}
        </div>
        {item.text ? (
          <div
            className="thread__text"
            dangerouslySetInnerHTML={{ __html: sanitizeCommentHtml(item.text) }}
          />
        ) : null}
        <div className="thread__comment-count">
          {commentCount} {pluralize(commentCount, 'comment')}
        </div>
      </header>
      <ol className="thread__comments">
        {shown.map((kidId) => (
          <li key={kidId}>
            <Comment id={kidId} depth={0} />
          </li>
        ))}
      </ol>
      {hasMore ? (
        <div
          ref={sentinelRef}
          className="thread__sentinel"
          data-testid="comments-sentinel"
          aria-hidden="true"
        />
      ) : null}
    </article>
  );
}
